export const SET_PROFILE = "SET_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const SET_LOADING = "SET_LOADING";
export const CLEAR_LOADING = "CLEAR_LOADING";

export const FETCH_PROFILE_FAILED = 'FETCH_PROFILE_FAILED';

export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS';
export const UPDATE_ROLE_FAIL = 'UPDATE_ROLE_FAIL';
export const UPDATE_ACTIVE_STATUS_SUCCESS = 'UPDATE_ACTIVE_STATUS_SUCCESS';
export const UPDATE_ACTIVE_STATUS_FAIL = 'UPDATE_ACTIVE_STATUS_FAIL';
